// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYkWxZww-wVN6DXmRUa4Rxsi7hU3JrZ9Q',
    appId: '1:1042783564992:android:a472e86e1ce605ed62e925',
    messagingSenderId: '1042783564992',
    projectId: 'daily-task-planner-935f5',
    storageBucket: 'daily-task-planner-935f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT5b9umrTo_Hlj9zHPR4fCGMlKwgWbYD0',
    appId: '1:1042783564992:ios:ad6be76336c0621862e925',
    messagingSenderId: '1042783564992',
    projectId: 'daily-task-planner-935f5',
    storageBucket: 'daily-task-planner-935f5.appspot.com',
    androidClientId: '1042783564992-1r6v2g313p0vd2gb54madgvaq2pfm0bs.apps.googleusercontent.com',
    iosClientId: '1042783564992-9hnco30alkr66npgt8it6huslb9s49j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayumi',
  );

}